package com.dev.mywebrtc.service

enum class MainServiceActions {
    START_SERVICE, STOP_SERVICE, ACTION_EXIT, SETUP_VIEWS, END_CALL, SWITCH_CAMERA, TOGGLE_AUDIO, TOGGLE_VIDEO, TOGGLE_AUDIO_DEVICE, TOGGLE_SCREEN_SHARE;

}